name: run pythong action
on:
  workflow_dispatch:
jobs:
  run_pythong_action:
    runs-on: ubuntu-latest
    container: # TODO: download this docker inside the runner docker instead and cache it
      image: selenium/standalone-chrome
      #env:
      #  FOO: bar
      #ports:
      #  - 80
      #volumes:
      #  - my_docker_volume:/volume_mount
      options: --user root
    steps:
      #- name: Cache Docker images.
      #  uses: ScribeMD/docker-cache@0.3.7
      #  with:
      #    key: docker-${{ runner.os }}
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Install Selenium in Pythong
        run: pip3 install selenium
      - name: Run script
        run: python3 test.py
