name: run pythong action
on:
  workflow_dispatch:
jobs:
  run_pythong_action:
    runs-on: ubuntu-latest
    container: # TODO: download this docker inside the runner docker instead and cache it
      image: selenium/standalone-chrome
      env:
        SE_OFFLINE: false
      #ports:
      #  - 80
      #volumes:
      #  - my_docker_volume:/volume_mount
      options: --user root
    steps:
      #- name: Cache Docker images.
      #  uses: ScribeMD/docker-cache@0.3.7
      #  with:
      #    key: docker-${{ runner.os }}
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Install Selenium in Pythong # TODO just create an image with this added
        run: wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && python3 -m pip install selenium
      - name: Verify Chrome
        run: which google-chrome-stable || google-chrome-stable --headless
      - name: Run script
        run: python3 test.py
