name: run pythong action
on:
  workflow_dispatch:
jobs:
  run_pythong_action:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome
      #env:
      #  FOO: bar
      #ports:
      #  - 80
      #volumes:
      #  - my_docker_volume:/volume_mount
      options: --user root
    steps:
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles(paths) }}
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Run script
        run: python3 test.py
