name: run pythong action
on:
  workflow_dispatch:
jobs:
  run_pythong_action:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4444:4444
        options: --shm-size="2g"

    steps:
    - uses: actions/checkout@v2
    - name: Get IP Address
      run: echo "##[set-output name=ip;]$(ifconfig eth0 | grep 'inet [0-9\.]* ' -o | sed 's/[^0-9\.]//g')"
      id: ip_addr 
      
    - name: Setup Pyhon
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Python dependencies
      run: wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && python3 -m pip install selenium

    - name: Run Tests
      run: python3 test.py --backend http://localhost:8080/ --frontend http://${{ steps.ip_addr.outputs.ip }}:4200 --selenium http://localhost:4444/wd/hub
